name: Continuous Integration

on: [push]

jobs:
  test:
    name: Test by running cookiecutter
    runs-on: ubuntu-latest
    env:
      TEST_PROJECT: foundation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'orbyter-cookiecutter'
      - name: Install cookiecutter
        run: pip install cookiecutter
      - name: Cut a cookie (repo)
        run: "python -m cookiecutter --no-input orbyter-cookiecutter project_name=$TEST_PROJECT repo_name=$TEST_PROJECT"
      - name: Build project containers (make dev-start)
        working-directory: ${{env.TEST_PROJECT}}
        run: make dev-start
      - name: Run initial project tests (make ci)
        working-directory: ${{env.TEST_PROJECT}}
        run: make ci
